on:
  release:
    types: [published]

jobs:
  update-version-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - run: npm install
      - name: Update Version Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 620d354155ac64df287ca41978ed0596
          filename: version.json
          label: Version 
          message: ${{ github.ref }}
          color: blue
